# Generated by Django 5.0.8 on 2025-02-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mymodel_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
